-- entri "Ask your notes" suggested prompts. Per-user, LLM-generated FROM the
-- student's own cards so every suggestion is answerable by the grounded RAG.
-- Regenerated by the ingest worker whenever a new note lands (and lazily on
-- first chat visit if empty). Writes are admin-worker only; authenticated users
-- get SELECT — same posture as the concept graph.
CREATE TABLE public.chat_suggestions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  question    TEXT NOT NULL,
  topic       TEXT,                              -- the topic it draws on (UI label, optional)
  rank        SMALLINT NOT NULL DEFAULT 0,       -- display order
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX chat_suggestions_user_id_idx ON public.chat_suggestions (user_id, rank);

ALTER TABLE public.chat_suggestions ENABLE ROW LEVEL SECURITY;

-- Read-only for the owner; the worker/route write via the RLS-bypassing admin
-- client (scoped by user_id in code), so no write grant to authenticated.
CREATE POLICY "own chat_suggestions read" ON public.chat_suggestions
  FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()));

GRANT SELECT ON public.chat_suggestions TO authenticated;
